homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 30
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

# Enables configuration UI
config:

customizer:
  custom_ui: local

http:
  api_password: !secret pi_password
  ssl_certificate: !secret dns_ssl_certificate
  ssl_key: !secret dns_ssl_key
  base_url: !secret dns_base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

switch:
  - platform: tplink
    host: !secret tp_link_host

logger:

duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_access_token

neato:
  username: !secret neato_user
  password: !secret neato_password


remote:
  - platform: harmony
    name: Media Center
    host: 10.0.0.171
    activity: Watch TV

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

climate:
  - platform: generic_thermostat
    name: Living Room
    heater: switch.study_heater
    target_sensor: sensor.study_temperature

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    mqtt_topic: "owntracks/#"
    events_only: True
  - platform: ping
    new_device_defaults:
      track_new_devices: True
    consider_home: 600
    hosts:
      ben_ping: !secret ben_phone_ip
      riley_ping: !secret riley_phone_ip

binary_sensor:
  - platform: bayesian
    prior: 0.6
    name: 'Bayesian Presence Ben'
    probability_threshold: 0.82
    observations:
      - entity_id: 'device_tracker.ben_ping'
        prob_given_true: 0.9
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.ben_phone'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'home'

usps:
    username: !secret usps_username
    password: !secret usps_password
    driver: phantomjs
